[build]
  base = "pharmacy-frontend/"
  publish = "pharmacy-frontend/build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  REACT_APP_BACKEND_URL = "https://intarepharmacy-v3.onrender.com"